development:
  api_key: 599b62ef49381cb4eb50333c8118d3a8
  secret_key: ec16ebf171db9165747fda3f5431b2d1
  canvas_page_name: bettercarbon
 # callback_url: http://staging.travelerstable.com:8888
 # pretty_errors: true
 # set_asset_host_to_callback_url: true
 # tunnel:
 #     public_host_username: fooberryfoo
 #     public_host: staging.travelerstable.com
 #     public_port: 8888
 #     local_port: 3000
 #     server_alive_interval: 0
test:
  api_key: 599b62ef49381cb4eb50333c8118d3a8
  secret_key: ec16ebf171db9165747fda3f5431b2d1
  canvas_page_name: bettercarbon
production:
  api_key: 599b62ef49381cb4eb50333c8118d3a8
  secret_key: ec16ebf171db9165747fda3f5431b2d1
  canvas_page_name: bettercarbon
